from typing import List
from fastapi import APIRouter, Depends
from sqlalchemy.orm import Session

from app.database import get_db
from app.services.dashboard_service import DashboardService
from app.schemas.dashboard import (
    DashboardOverviewResponse,
    RiskTrendResponse,
    RiskAlertItem,
    CollectionsPerformanceResponse,
    LiquidityForecastResponse,
)

router = APIRouter(prefix="/dashboard", tags=["Dashboard"])

@router.get("/overview", response_model=DashboardOverviewResponse)
def get_dashboard_overview(db: Session = Depends(get_db)):
    """
    Returns the comprehensive financial intelligence overview for the FinSight AI dashboard,
    including executive KPIs, 6 agent states, coordinated network status, risk trends, alerts,
    collections, and 30-day liquidity forecast.
    """
    return DashboardService.get_overview(db)

@router.get("/risk-trend", response_model=RiskTrendResponse)
def get_risk_trend(db: Session = Depends(get_db)):
    """
    Returns the 6-month historical & current portfolio risk trends across Overall Risk,
    Credit Risk, and Collection Risk.
    """
    return DashboardService.get_risk_trend(db)

@router.get("/alerts", response_model=List[RiskAlertItem])
def get_risk_alerts(db: Session = Depends(get_db)):
    """
    Returns the latest AI risk alerts generated by the 6 coordinated intelligence agents.
    """
    return DashboardService.get_risk_alerts(db)

@router.get("/collections", response_model=CollectionsPerformanceResponse)
def get_collections_metrics(db: Session = Depends(get_db)):
    """
    Returns the collections performance breakdown including expected, actual, at-risk, and bucket distribution.
    """
    return DashboardService.get_collections_performance(db)

@router.get("/liquidity", response_model=LiquidityForecastResponse)
def get_liquidity_metrics(db: Session = Depends(get_db)):
    """
    Returns the 30-day liquidity forecast, cash inflows, outflows, and buffer ratio status.
    """
    return DashboardService.get_liquidity_forecast(db)
