import {
  DashboardOverview,
  RiskTrendData,
  RiskAlert,
  CollectionsPerformanceData,
  LiquidityForecastData,
  AgentCardData,
  AgentNetworkStatus,
  LoanApplicationItem,
  DemoUserItem,
} from '../types';

export const MOCK_OVERVIEW: DashboardOverview = {
  as_of: '28 Sep 2026, 10:45 IST',
  portfolio_status: 'Optimal / Coordinated Intelligence Active',
  kpis: [
    {
      id: 'aum',
      title: 'Assets Under Management',
      value: '₹842.6 Cr',
      numeric_value: 842.6,
      unit: 'Cr',
      change_pct: 8.4,
      change_direction: 'up',
      status: 'positive',
      subtext: '+8.4% vs last quarter',
      sparkline: [810, 815, 822, 830, 838, 842.6],
    },
    {
      id: 'loan_portfolio',
      title: 'Active Loan Book',
      value: '₹718.2 Cr',
      numeric_value: 718.2,
      unit: 'Cr',
      change_pct: 6.1,
      change_direction: 'up',
      status: 'positive',
      subtext: '+6.1% active retail book',
      sparkline: [690, 698, 705, 712, 715, 718.2],
    },
    {
      id: 'portfolio_risk',
      title: 'Portfolio Risk Level',
      value: 'Low / Optimal',
      numeric_value: 28.4,
      unit: 'Score',
      change_pct: -3.2,
      change_direction: 'down',
      status: 'positive',
      subtext: '-3.2% default likelihood',
      sparkline: [32, 31, 30, 29.5, 29, 28.4],
    },
    {
      id: 'gross_npa',
      title: 'Gross NPA Ratio',
      value: '1.82%',
      numeric_value: 1.82,
      unit: '%',
      change_pct: -0.15,
      change_direction: 'down',
      status: 'positive',
      subtext: 'Well below 3.0% threshold',
      sparkline: [2.1, 2.05, 1.98, 1.92, 1.88, 1.82],
    },
    {
      id: 'fraud_exposure',
      title: 'Fraud Under Review',
      value: '₹2.8 Cr',
      numeric_value: 2.8,
      unit: 'Cr',
      change_pct: -12.4,
      change_direction: 'down',
      status: 'positive',
      subtext: '12 active alerts under forensics',
      sparkline: [3.8, 3.5, 3.2, 3.0, 2.9, 2.8],
    },
    {
      id: 'collection_efficiency',
      title: 'Collection Efficiency',
      value: '94.7%',
      numeric_value: 94.7,
      unit: '%',
      change_pct: 1.8,
      change_direction: 'up',
      status: 'positive',
      subtext: '+1.8% vs monthly target',
      sparkline: [92.0, 92.8, 93.4, 93.9, 94.2, 94.7],
    },
  ],
  agents: [
    {
      id: 'credit_agent',
      name: 'Credit Intelligence Agent',
      short_name: 'Credit Appraisal',
      status: 'Optimal Assessment',
      status_type: 'positive',
      key_metric_label: 'Approval Rate',
      key_metric_value: '76.4%',
      secondary_metric_label: 'Mean PD',
      secondary_metric_value: '4.8%',
      trend: '+2.1% throughput',
      trend_direction: 'up',
      icon_name: 'CreditCard',
      action_label: 'Underwrite Queue',
      route: '/underwriting-queue',
      last_updated: 'Just now',
      execution_time_ms: 142,
    },
    {
      id: 'fraud_agent',
      name: 'Fraud Intelligence Agent',
      short_name: 'Fraud Forensics',
      status: 'Elevated Scan Active',
      status_type: 'elevated',
      key_metric_label: 'Screened Apps',
      key_metric_value: '1,420',
      secondary_metric_label: 'Flagged High-Risk',
      secondary_metric_value: '12 Cases',
      trend: 'Zero false negatives',
      trend_direction: 'neutral',
      icon_name: 'ShieldAlert',
      action_label: 'Forensic Review',
      route: '/fraud',
      last_updated: '3m ago',
      execution_time_ms: 88,
    },
    {
      id: 'collections_agent',
      name: 'Collections Intelligence Agent',
      short_name: 'Delinquency Recovery',
      status: 'Proactive Outreach',
      status_type: 'positive',
      key_metric_label: 'Current Efficiency',
      key_metric_value: '94.7%',
      secondary_metric_label: 'PTP Honored',
      secondary_metric_value: '88.4%',
      trend: '+₹42.8 Cr recovered',
      trend_direction: 'up',
      icon_name: 'PiggyBank',
      action_label: 'Collections Desk',
      route: '/collections',
      last_updated: '1m ago',
      execution_time_ms: 210,
    },
    {
      id: 'customer_agent',
      name: 'Customer Intelligence Agent',
      short_name: 'Borrower 360',
      status: 'Retention Active',
      status_type: 'normal',
      key_metric_label: 'Active Borrowers',
      key_metric_value: '48,250',
      secondary_metric_label: 'Churn Risk',
      secondary_metric_value: '3.2%',
      trend: '+5.4% loyalty score',
      trend_direction: 'up',
      icon_name: 'Users',
      action_label: 'Inspect Cohorts',
      route: '/customer',
      last_updated: '5m ago',
      execution_time_ms: 165,
    },
    {
      id: 'risk_agent',
      name: 'Risk Intelligence Agent',
      short_name: 'Portfolio Governance',
      status: 'Stress Shock Passed',
      status_type: 'positive',
      key_metric_label: 'Stress Loss Ratio',
      key_metric_value: '1.42%',
      secondary_metric_label: 'HHI Concentration',
      secondary_metric_value: '0.082',
      trend: 'Compliant with RBI Limit',
      trend_direction: 'neutral',
      icon_name: 'Activity',
      action_label: 'Simulate Shocks',
      route: '/risk',
      last_updated: 'Just now',
      execution_time_ms: 320,
    },
    {
      id: 'liquidity_agent',
      name: 'Liquidity Intelligence Agent',
      short_name: 'Treasury & ALM',
      status: 'Surplus Projected',
      status_type: 'positive',
      key_metric_label: 'LCR Buffer Ratio',
      key_metric_value: '138.4%',
      secondary_metric_label: '30-Day Surplus',
      secondary_metric_value: '+₹42.0 Lakhs',
      trend: 'Floor: 100% (Passed)',
      trend_direction: 'up',
      icon_name: 'Coins',
      action_label: 'View ALM Gap',
      route: '/liquidity',
      last_updated: '2m ago',
      execution_time_ms: 95,
    },
  ],
  network: {
    pipeline_state: 'Fully Synchronized',
    sync_rate: 99.8,
    last_sync_timestamp: 'Just now',
    nodes: [
      { id: '1', name: 'Sales & Ingestion', role: 'Data Ingestion', status: 'Healthy', latency_ms: 18, data_out: '12 apps/min' },
      { id: '2', name: 'KYC & AML Engine', role: 'Identity Screening', status: 'Healthy', latency_ms: 42, data_out: '99.4% pass' },
      { id: '3', name: 'Credit Decisioning', role: 'Underwriting', status: 'Healthy', latency_ms: 64, data_out: '76% auto' },
      { id: '4', name: 'Fraud Sentinel', role: 'Forensics', status: 'Healthy', latency_ms: 22, data_out: '0 collisions' },
      { id: '5', name: 'Portfolio Risk Desk', role: 'Stress & HHI', status: 'Healthy', latency_ms: 55, data_out: 'Stable' },
      { id: '6', name: 'Treasury & Liquidity', role: 'Cash Matching', status: 'Healthy', latency_ms: 31, data_out: '+₹42.0L' },
    ],
    pipeline_order: ['Sales', 'KYC', 'Credit', 'Fraud', 'Risk', 'Liquidity'],
  },
  risk_trend: {
    timeframe: 'Last 6 Months',
    trend_summary: 'Overall portfolio risk score declined by 3.2% due to tighter CIBIL thresholds and accelerated DPD rollbacks.',
    current_overall_score: 28.4,
    series: [
      { date: '2026-04', month_label: 'Apr 26', overall_risk_score: 34.2, credit_risk_score: 36.1, collection_risk_score: 32.5, npa_risk_score: 2.1 },
      { date: '2026-05', month_label: 'May 26', overall_risk_score: 32.8, credit_risk_score: 34.5, collection_risk_score: 31.0, npa_risk_score: 2.05 },
      { date: '2026-06', month_label: 'Jun 26', overall_risk_score: 31.5, credit_risk_score: 33.0, collection_risk_score: 30.2, npa_risk_score: 1.98 },
      { date: '2026-07', month_label: 'Jul 26', overall_risk_score: 30.2, credit_risk_score: 31.8, collection_risk_score: 29.1, npa_risk_score: 1.92 },
      { date: '2026-08', month_label: 'Aug 26', overall_risk_score: 29.1, credit_risk_score: 30.4, collection_risk_score: 28.3, npa_risk_score: 1.88 },
      { date: '2026-09', month_label: 'Sep 26', overall_risk_score: 28.4, credit_risk_score: 29.6, collection_risk_score: 27.5, npa_risk_score: 1.82 },
    ],
  },
  risk_alerts: [
    {
      id: 'alt-1',
      severity: 'High',
      message: 'MSME Loan Portfolio: Industrial manufacturing sector concentration approaching 28.4% limit (Ceiling 30%).',
      timestamp: '12m ago',
      responsible_agent: 'Risk Sentinel Agent',
      category: 'Concentration Risk',
      is_acknowledged: false,
    },
    {
      id: 'alt-2',
      severity: 'Medium',
      message: 'Retail Personal Loan cohort in Delhi-NCR cluster showed 1.4% higher early DPD roll rates over the weekend.',
      timestamp: '34m ago',
      responsible_agent: 'Collections Intelligence Agent',
      category: 'Delinquency Drift',
      is_acknowledged: false,
    },
    {
      id: 'alt-3',
      severity: 'Critical',
      message: 'Detected synthetic device fingerprint collision across 3 concurrent digital onboarding applications.',
      timestamp: '1h ago',
      responsible_agent: 'Fraud Forensics Agent',
      category: 'Identity Fraud',
      is_acknowledged: false,
    },
    {
      id: 'alt-4',
      severity: 'Low',
      message: 'Monthly LCR cash buffer comfortably exceeds statutory threshold at 138.4% (Floor 100%).',
      timestamp: '2h ago',
      responsible_agent: 'Liquidity Agent',
      category: 'Regulatory ALM',
      is_acknowledged: true,
    },
  ],
  collections: {
    current_month_collected_cr: 42.8,
    current_month_collected_formatted: '₹42.8 Cr',
    collection_efficiency_pct: 94.7,
    efficiency_target_pct: 96.0,
    expected_collections_cr: 45.2,
    actual_collections_cr: 42.8,
    at_risk_receivables_cr: 18.4,
    resolution_rate_pct: 88.4,
    breakdown_by_bucket: {
      '0-30 DPD': 78.4,
      '31-60 DPD': 14.2,
      '61-90 DPD': 5.6,
      '90+ DPD': 1.8,
    },
    trend_direction: 'improving',
  },
  liquidity: {
    timeframe: 'Next 30 Days',
    forecast_status: 'Surplus',
    current_liquidity_cr: 126.4,
    current_liquidity_formatted: '₹126.4 Cr',
    expected_inflows_cr: 94.8,
    expected_outflows_cr: 52.8,
    forecasted_liquidity_cr: 168.4,
    liquidity_buffer_ratio: 1.45,
    stress_test_status: 'Compliant (Shock-Proof)',
    projections: [
      { period: 'Week 1', inflows_cr: 24.5, outflows_cr: 12.0, net_balance_cr: 138.9 },
      { period: 'Week 2', inflows_cr: 22.8, outflows_cr: 14.5, net_balance_cr: 147.2 },
      { period: 'Week 3', inflows_cr: 25.1, outflows_cr: 11.8, net_balance_cr: 160.5 },
      { period: 'Week 4', inflows_cr: 22.4, outflows_cr: 14.5, net_balance_cr: 168.4 },
    ],
  },
};

export const MOCK_APPLICATIONS: LoanApplicationItem[] = [
  {
    id: 1,
    application_id: 'APP-260901-B892',
    customer_id: 101,
    customer_name: 'Sunil Kumar Enterprises',
    customer_identifier: 'CUST-IND-9912',
    product_type: 'MSME Business Loan',
    requested_amount: 2500000,
    requested_tenure: 36,
    customer_cibil: 768,
    risk_score: 24,
    default_probability: 0.024,
    status: 'Under_Review',
    created_at: '2026-09-28T08:30:00Z',
  },
  {
    id: 2,
    application_id: 'APP-260902-A104',
    customer_id: 102,
    customer_name: 'Anita Deshmukh',
    customer_identifier: 'CUST-RET-5481',
    product_type: 'Personal Loan',
    requested_amount: 500000,
    requested_tenure: 24,
    customer_cibil: 742,
    risk_score: 38,
    default_probability: 0.038,
    status: 'Approved',
    created_at: '2026-09-28T07:15:00Z',
  },
  {
    id: 3,
    application_id: 'APP-260903-V721',
    customer_id: 103,
    customer_name: 'Karan Mehra Logistics',
    customer_identifier: 'CUST-COM-2104',
    product_type: 'Commercial Vehicle Loan',
    requested_amount: 1800000,
    requested_tenure: 48,
    customer_cibil: 712,
    risk_score: 45,
    default_probability: 0.045,
    status: 'Documents_Required',
    created_at: '2026-09-27T16:40:00Z',
  },
  {
    id: 4,
    application_id: 'APP-260904-G389',
    customer_id: 104,
    customer_name: 'Pooja Agarwal',
    customer_identifier: 'CUST-RET-8819',
    product_type: 'Gold Loan',
    requested_amount: 350000,
    requested_tenure: 12,
    customer_cibil: 795,
    risk_score: 12,
    default_probability: 0.012,
    status: 'Disbursed',
    created_at: '2026-09-27T14:10:00Z',
  },
  {
    id: 5,
    application_id: 'APP-260905-M562',
    customer_id: 105,
    customer_name: 'Apex Precision Tools Pvt Ltd',
    customer_identifier: 'CUST-CORP-0932',
    product_type: 'MSME Working Capital',
    requested_amount: 5000000,
    requested_tenure: 36,
    customer_cibil: 685,
    risk_score: 62,
    default_probability: 0.062,
    status: 'Disbursement_Pending',
    created_at: '2026-09-27T11:25:00Z',
  },
  {
    id: 6,
    application_id: 'APP-260906-R118',
    customer_id: 106,
    customer_name: 'Rajesh K. Sharma',
    customer_identifier: 'CUST-RET-3391',
    product_type: 'Consumer Durable Loan',
    requested_amount: 120000,
    requested_tenure: 18,
    customer_cibil: 610,
    risk_score: 98,
    default_probability: 0.098,
    status: 'Rejected',
    created_at: '2026-09-26T18:00:00Z',
  },
];
