"""initial_nbfc_schema

Revision ID: 5dd26776e8f8
Revises: 
Create Date: 2026-09-26 10:33:33.769772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5dd26776e8f8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.String(length=50), nullable=False),
    sa.Column('agent_name', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('execution_time_ms', sa.Integer(), nullable=True),
    sa.Column('entities_evaluated', sa.Integer(), nullable=True),
    sa.Column('anomalies_detected', sa.Integer(), nullable=True),
    sa.Column('metrics_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_runs_agent_name'), 'agent_runs', ['agent_name'], unique=False)
    op.create_index(op.f('ix_agent_runs_created_at'), 'agent_runs', ['created_at'], unique=False)
    op.create_index(op.f('ix_agent_runs_id'), 'agent_runs', ['id'], unique=False)
    op.create_index(op.f('ix_agent_runs_run_id'), 'agent_runs', ['run_id'], unique=True)
    op.create_index(op.f('ix_agent_runs_status'), 'agent_runs', ['status'], unique=False)
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.String(length=50), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone_hash', sa.String(length=64), nullable=True),
    sa.Column('address_hash', sa.String(length=64), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('occupation', sa.String(length=100), nullable=True),
    sa.Column('employment_type', sa.String(length=50), nullable=True),
    sa.Column('income', sa.Float(), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('credit_score', sa.Integer(), nullable=True),
    sa.Column('existing_loans', sa.Integer(), nullable=True),
    sa.Column('credit_utilization', sa.Float(), nullable=True),
    sa.Column('bank_balance', sa.Float(), nullable=True),
    sa.Column('income_stability', sa.Float(), nullable=True),
    sa.Column('previous_defaults', sa.Integer(), nullable=True),
    sa.Column('risk_tier', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_address_hash'), 'customers', ['address_hash'], unique=False)
    op.create_index(op.f('ix_customers_credit_score'), 'customers', ['credit_score'], unique=False)
    op.create_index(op.f('ix_customers_customer_id'), 'customers', ['customer_id'], unique=True)
    op.create_index(op.f('ix_customers_email'), 'customers', ['email'], unique=False)
    op.create_index(op.f('ix_customers_id'), 'customers', ['id'], unique=False)
    op.create_index(op.f('ix_customers_phone_hash'), 'customers', ['phone_hash'], unique=False)
    op.create_index(op.f('ix_customers_risk_tier'), 'customers', ['risk_tier'], unique=False)
    op.create_table('liquidity_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('record_date', sa.Date(), nullable=True),
    sa.Column('available_liquidity_cr', sa.Float(), nullable=False),
    sa.Column('expected_inflows_cr', sa.Float(), nullable=False),
    sa.Column('expected_outflows_cr', sa.Float(), nullable=False),
    sa.Column('forecasted_liquidity_cr', sa.Float(), nullable=False),
    sa.Column('liquidity_buffer_ratio', sa.Float(), nullable=True),
    sa.Column('stress_test_status', sa.String(length=50), nullable=True),
    sa.Column('forecast_30d_trend', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_liquidity_records_id'), 'liquidity_records', ['id'], unique=False)
    op.create_index(op.f('ix_liquidity_records_record_date'), 'liquidity_records', ['record_date'], unique=True)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notification_id', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('responsible_agent', sa.String(length=50), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('related_entity_type', sa.String(length=50), nullable=True),
    sa.Column('related_entity_id', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_category'), 'notifications', ['category'], unique=False)
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index(op.f('ix_notifications_is_read'), 'notifications', ['is_read'], unique=False)
    op.create_index(op.f('ix_notifications_notification_id'), 'notifications', ['notification_id'], unique=True)
    op.create_index(op.f('ix_notifications_severity'), 'notifications', ['severity'], unique=False)
    op.create_table('risk_signals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('signal_id', sa.String(length=50), nullable=False),
    sa.Column('signal_type', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('metric_impact', sa.String(length=100), nullable=True),
    sa.Column('responsible_agent', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('detected_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_signals_detected_at'), 'risk_signals', ['detected_at'], unique=False)
    op.create_index(op.f('ix_risk_signals_id'), 'risk_signals', ['id'], unique=False)
    op.create_index(op.f('ix_risk_signals_responsible_agent'), 'risk_signals', ['responsible_agent'], unique=False)
    op.create_index(op.f('ix_risk_signals_severity'), 'risk_signals', ['severity'], unique=False)
    op.create_index(op.f('ix_risk_signals_signal_id'), 'risk_signals', ['signal_id'], unique=True)
    op.create_index(op.f('ix_risk_signals_signal_type'), 'risk_signals', ['signal_type'], unique=False)
    op.create_index(op.f('ix_risk_signals_status'), 'risk_signals', ['status'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'CREDIT_OFFICER', 'RISK_MANAGER', 'COLLECTION_MANAGER', 'FINANCE_MANAGER', 'ANALYST', 'AUDITOR', name='userrole'), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('agent_decisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('decision_id', sa.String(length=50), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=True),
    sa.Column('agent_name', sa.String(length=50), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=50), nullable=False),
    sa.Column('decision', sa.String(length=100), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('explanation_json', sa.Text(), nullable=True),
    sa.Column('coordinated_with', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['agent_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_decisions_agent_name'), 'agent_decisions', ['agent_name'], unique=False)
    op.create_index(op.f('ix_agent_decisions_created_at'), 'agent_decisions', ['created_at'], unique=False)
    op.create_index(op.f('ix_agent_decisions_decision_id'), 'agent_decisions', ['decision_id'], unique=True)
    op.create_index(op.f('ix_agent_decisions_entity_id'), 'agent_decisions', ['entity_id'], unique=False)
    op.create_index(op.f('ix_agent_decisions_id'), 'agent_decisions', ['id'], unique=False)
    op.create_index(op.f('ix_agent_decisions_run_id'), 'agent_decisions', ['run_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource', sa.String(length=100), nullable=False),
    sa.Column('details_json', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('customer_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('financial_health_score', sa.Float(), nullable=True),
    sa.Column('churn_risk', sa.Float(), nullable=True),
    sa.Column('segment', sa.String(length=50), nullable=True),
    sa.Column('behavioral_score', sa.Float(), nullable=True),
    sa.Column('avg_monthly_spend', sa.Float(), nullable=True),
    sa.Column('savings_ratio', sa.Float(), nullable=True),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customer_id')
    )
    op.create_index(op.f('ix_customer_profiles_id'), 'customer_profiles', ['id'], unique=False)
    op.create_table('loan_applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.String(length=50), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('product_type', sa.String(length=50), nullable=False),
    sa.Column('requested_amount', sa.Float(), nullable=False),
    sa.Column('requested_tenure', sa.Integer(), nullable=False),
    sa.Column('purpose', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('device_id', sa.String(length=64), nullable=True),
    sa.Column('phone_hash', sa.String(length=64), nullable=True),
    sa.Column('address_hash', sa.String(length=64), nullable=True),
    sa.Column('application_velocity', sa.Integer(), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('default_probability', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_loan_applications_address_hash'), 'loan_applications', ['address_hash'], unique=False)
    op.create_index(op.f('ix_loan_applications_application_id'), 'loan_applications', ['application_id'], unique=True)
    op.create_index(op.f('ix_loan_applications_created_at'), 'loan_applications', ['created_at'], unique=False)
    op.create_index(op.f('ix_loan_applications_customer_id'), 'loan_applications', ['customer_id'], unique=False)
    op.create_index(op.f('ix_loan_applications_device_id'), 'loan_applications', ['device_id'], unique=False)
    op.create_index(op.f('ix_loan_applications_id'), 'loan_applications', ['id'], unique=False)
    op.create_index(op.f('ix_loan_applications_phone_hash'), 'loan_applications', ['phone_hash'], unique=False)
    op.create_index(op.f('ix_loan_applications_status'), 'loan_applications', ['status'], unique=False)
    op.create_table('loans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('loan_id', sa.String(length=50), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('product_type', sa.String(length=50), nullable=True),
    sa.Column('loan_amount', sa.Float(), nullable=False),
    sa.Column('interest_rate', sa.Float(), nullable=False),
    sa.Column('loan_tenure', sa.Integer(), nullable=False),
    sa.Column('emi', sa.Float(), nullable=False),
    sa.Column('outstanding_balance', sa.Float(), nullable=False),
    sa.Column('dpd', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('disbursed_date', sa.DateTime(), nullable=True),
    sa.Column('maturity_date', sa.DateTime(), nullable=True),
    sa.Column('previous_defaults', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_loans_customer_id'), 'loans', ['customer_id'], unique=False)
    op.create_index(op.f('ix_loans_dpd'), 'loans', ['dpd'], unique=False)
    op.create_index(op.f('ix_loans_id'), 'loans', ['id'], unique=False)
    op.create_index(op.f('ix_loans_loan_id'), 'loans', ['loan_id'], unique=True)
    op.create_index(op.f('ix_loans_product_type'), 'loans', ['product_type'], unique=False)
    op.create_index(op.f('ix_loans_status'), 'loans', ['status'], unique=False)
    op.create_table('collection_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('collection_id', sa.String(length=50), nullable=False),
    sa.Column('loan_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('overdue_amount', sa.Float(), nullable=False),
    sa.Column('dpd', sa.Integer(), nullable=True),
    sa.Column('collection_risk_score', sa.Float(), nullable=True),
    sa.Column('collection_probability', sa.Float(), nullable=True),
    sa.Column('recommended_strategy', sa.String(length=100), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.Column('collection_attempts', sa.Integer(), nullable=True),
    sa.Column('promised_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['loan_id'], ['loans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collection_records_collection_id'), 'collection_records', ['collection_id'], unique=True)
    op.create_index(op.f('ix_collection_records_customer_id'), 'collection_records', ['customer_id'], unique=False)
    op.create_index(op.f('ix_collection_records_dpd'), 'collection_records', ['dpd'], unique=False)
    op.create_index(op.f('ix_collection_records_id'), 'collection_records', ['id'], unique=False)
    op.create_index(op.f('ix_collection_records_loan_id'), 'collection_records', ['loan_id'], unique=False)
    op.create_index(op.f('ix_collection_records_priority'), 'collection_records', ['priority'], unique=False)
    op.create_index(op.f('ix_collection_records_status'), 'collection_records', ['status'], unique=False)
    op.create_table('credit_assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assessment_id', sa.String(length=50), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('loan_id', sa.Integer(), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('default_probability', sa.Float(), nullable=False),
    sa.Column('dti_ratio', sa.Float(), nullable=False),
    sa.Column('factors_json', sa.Text(), nullable=True),
    sa.Column('recommendation', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['loan_id'], ['loans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credit_assessments_assessment_id'), 'credit_assessments', ['assessment_id'], unique=True)
    op.create_index(op.f('ix_credit_assessments_created_at'), 'credit_assessments', ['created_at'], unique=False)
    op.create_index(op.f('ix_credit_assessments_customer_id'), 'credit_assessments', ['customer_id'], unique=False)
    op.create_index(op.f('ix_credit_assessments_id'), 'credit_assessments', ['id'], unique=False)
    op.create_index(op.f('ix_credit_assessments_loan_id'), 'credit_assessments', ['loan_id'], unique=False)
    op.create_table('fraud_alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alert_id', sa.String(length=50), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=True),
    sa.Column('loan_id', sa.Integer(), nullable=True),
    sa.Column('alert_type', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('rule_triggered', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('exposure_amount', sa.Float(), nullable=True),
    sa.Column('details_json', sa.Text(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['loan_applications.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['loan_id'], ['loans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fraud_alerts_alert_id'), 'fraud_alerts', ['alert_id'], unique=True)
    op.create_index(op.f('ix_fraud_alerts_alert_type'), 'fraud_alerts', ['alert_type'], unique=False)
    op.create_index(op.f('ix_fraud_alerts_application_id'), 'fraud_alerts', ['application_id'], unique=False)
    op.create_index(op.f('ix_fraud_alerts_created_at'), 'fraud_alerts', ['created_at'], unique=False)
    op.create_index(op.f('ix_fraud_alerts_customer_id'), 'fraud_alerts', ['customer_id'], unique=False)
    op.create_index(op.f('ix_fraud_alerts_id'), 'fraud_alerts', ['id'], unique=False)
    op.create_index(op.f('ix_fraud_alerts_loan_id'), 'fraud_alerts', ['loan_id'], unique=False)
    op.create_index(op.f('ix_fraud_alerts_severity'), 'fraud_alerts', ['severity'], unique=False)
    op.create_index(op.f('ix_fraud_alerts_status'), 'fraud_alerts', ['status'], unique=False)
    op.create_table('repayments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repayment_id', sa.String(length=64), nullable=False),
    sa.Column('loan_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('due_date', sa.DateTime(), nullable=False),
    sa.Column('repayment_date', sa.DateTime(), nullable=True),
    sa.Column('amount_due', sa.Float(), nullable=False),
    sa.Column('amount_paid', sa.Float(), nullable=True),
    sa.Column('dpd', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('collection_attempts', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['loan_id'], ['loans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repayments_customer_id'), 'repayments', ['customer_id'], unique=False)
    op.create_index(op.f('ix_repayments_dpd'), 'repayments', ['dpd'], unique=False)
    op.create_index(op.f('ix_repayments_due_date'), 'repayments', ['due_date'], unique=False)
    op.create_index(op.f('ix_repayments_id'), 'repayments', ['id'], unique=False)
    op.create_index(op.f('ix_repayments_loan_id'), 'repayments', ['loan_id'], unique=False)
    op.create_index(op.f('ix_repayments_repayment_id'), 'repayments', ['repayment_id'], unique=True)
    op.create_index(op.f('ix_repayments_status'), 'repayments', ['status'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.String(length=64), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('loan_id', sa.Integer(), nullable=True),
    sa.Column('transaction_amount', sa.Float(), nullable=False),
    sa.Column('transaction_type', sa.String(length=50), nullable=True),
    sa.Column('transaction_timestamp', sa.DateTime(), nullable=True),
    sa.Column('channel', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['loan_id'], ['loans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_customer_id'), 'transactions', ['customer_id'], unique=False)
    op.create_index(op.f('ix_transactions_id'), 'transactions', ['id'], unique=False)
    op.create_index(op.f('ix_transactions_loan_id'), 'transactions', ['loan_id'], unique=False)
    op.create_index(op.f('ix_transactions_status'), 'transactions', ['status'], unique=False)
    op.create_index(op.f('ix_transactions_transaction_id'), 'transactions', ['transaction_id'], unique=True)
    op.create_index(op.f('ix_transactions_transaction_timestamp'), 'transactions', ['transaction_timestamp'], unique=False)
    op.create_index(op.f('ix_transactions_transaction_type'), 'transactions', ['transaction_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_transaction_type'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_transaction_timestamp'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_transaction_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_status'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_loan_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_customer_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_repayments_status'), table_name='repayments')
    op.drop_index(op.f('ix_repayments_repayment_id'), table_name='repayments')
    op.drop_index(op.f('ix_repayments_loan_id'), table_name='repayments')
    op.drop_index(op.f('ix_repayments_id'), table_name='repayments')
    op.drop_index(op.f('ix_repayments_due_date'), table_name='repayments')
    op.drop_index(op.f('ix_repayments_dpd'), table_name='repayments')
    op.drop_index(op.f('ix_repayments_customer_id'), table_name='repayments')
    op.drop_table('repayments')
    op.drop_index(op.f('ix_fraud_alerts_status'), table_name='fraud_alerts')
    op.drop_index(op.f('ix_fraud_alerts_severity'), table_name='fraud_alerts')
    op.drop_index(op.f('ix_fraud_alerts_loan_id'), table_name='fraud_alerts')
    op.drop_index(op.f('ix_fraud_alerts_id'), table_name='fraud_alerts')
    op.drop_index(op.f('ix_fraud_alerts_customer_id'), table_name='fraud_alerts')
    op.drop_index(op.f('ix_fraud_alerts_created_at'), table_name='fraud_alerts')
    op.drop_index(op.f('ix_fraud_alerts_application_id'), table_name='fraud_alerts')
    op.drop_index(op.f('ix_fraud_alerts_alert_type'), table_name='fraud_alerts')
    op.drop_index(op.f('ix_fraud_alerts_alert_id'), table_name='fraud_alerts')
    op.drop_table('fraud_alerts')
    op.drop_index(op.f('ix_credit_assessments_loan_id'), table_name='credit_assessments')
    op.drop_index(op.f('ix_credit_assessments_id'), table_name='credit_assessments')
    op.drop_index(op.f('ix_credit_assessments_customer_id'), table_name='credit_assessments')
    op.drop_index(op.f('ix_credit_assessments_created_at'), table_name='credit_assessments')
    op.drop_index(op.f('ix_credit_assessments_assessment_id'), table_name='credit_assessments')
    op.drop_table('credit_assessments')
    op.drop_index(op.f('ix_collection_records_status'), table_name='collection_records')
    op.drop_index(op.f('ix_collection_records_priority'), table_name='collection_records')
    op.drop_index(op.f('ix_collection_records_loan_id'), table_name='collection_records')
    op.drop_index(op.f('ix_collection_records_id'), table_name='collection_records')
    op.drop_index(op.f('ix_collection_records_dpd'), table_name='collection_records')
    op.drop_index(op.f('ix_collection_records_customer_id'), table_name='collection_records')
    op.drop_index(op.f('ix_collection_records_collection_id'), table_name='collection_records')
    op.drop_table('collection_records')
    op.drop_index(op.f('ix_loans_status'), table_name='loans')
    op.drop_index(op.f('ix_loans_product_type'), table_name='loans')
    op.drop_index(op.f('ix_loans_loan_id'), table_name='loans')
    op.drop_index(op.f('ix_loans_id'), table_name='loans')
    op.drop_index(op.f('ix_loans_dpd'), table_name='loans')
    op.drop_index(op.f('ix_loans_customer_id'), table_name='loans')
    op.drop_table('loans')
    op.drop_index(op.f('ix_loan_applications_status'), table_name='loan_applications')
    op.drop_index(op.f('ix_loan_applications_phone_hash'), table_name='loan_applications')
    op.drop_index(op.f('ix_loan_applications_id'), table_name='loan_applications')
    op.drop_index(op.f('ix_loan_applications_device_id'), table_name='loan_applications')
    op.drop_index(op.f('ix_loan_applications_customer_id'), table_name='loan_applications')
    op.drop_index(op.f('ix_loan_applications_created_at'), table_name='loan_applications')
    op.drop_index(op.f('ix_loan_applications_application_id'), table_name='loan_applications')
    op.drop_index(op.f('ix_loan_applications_address_hash'), table_name='loan_applications')
    op.drop_table('loan_applications')
    op.drop_index(op.f('ix_customer_profiles_id'), table_name='customer_profiles')
    op.drop_table('customer_profiles')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_agent_decisions_run_id'), table_name='agent_decisions')
    op.drop_index(op.f('ix_agent_decisions_id'), table_name='agent_decisions')
    op.drop_index(op.f('ix_agent_decisions_entity_id'), table_name='agent_decisions')
    op.drop_index(op.f('ix_agent_decisions_decision_id'), table_name='agent_decisions')
    op.drop_index(op.f('ix_agent_decisions_created_at'), table_name='agent_decisions')
    op.drop_index(op.f('ix_agent_decisions_agent_name'), table_name='agent_decisions')
    op.drop_table('agent_decisions')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_risk_signals_status'), table_name='risk_signals')
    op.drop_index(op.f('ix_risk_signals_signal_type'), table_name='risk_signals')
    op.drop_index(op.f('ix_risk_signals_signal_id'), table_name='risk_signals')
    op.drop_index(op.f('ix_risk_signals_severity'), table_name='risk_signals')
    op.drop_index(op.f('ix_risk_signals_responsible_agent'), table_name='risk_signals')
    op.drop_index(op.f('ix_risk_signals_id'), table_name='risk_signals')
    op.drop_index(op.f('ix_risk_signals_detected_at'), table_name='risk_signals')
    op.drop_table('risk_signals')
    op.drop_index(op.f('ix_notifications_severity'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_notification_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_is_read'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_category'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_liquidity_records_record_date'), table_name='liquidity_records')
    op.drop_index(op.f('ix_liquidity_records_id'), table_name='liquidity_records')
    op.drop_table('liquidity_records')
    op.drop_index(op.f('ix_customers_risk_tier'), table_name='customers')
    op.drop_index(op.f('ix_customers_phone_hash'), table_name='customers')
    op.drop_index(op.f('ix_customers_id'), table_name='customers')
    op.drop_index(op.f('ix_customers_email'), table_name='customers')
    op.drop_index(op.f('ix_customers_customer_id'), table_name='customers')
    op.drop_index(op.f('ix_customers_credit_score'), table_name='customers')
    op.drop_index(op.f('ix_customers_address_hash'), table_name='customers')
    op.drop_table('customers')
    op.drop_index(op.f('ix_agent_runs_status'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_run_id'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_id'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_created_at'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_agent_name'), table_name='agent_runs')
    op.drop_table('agent_runs')
    # ### end Alembic commands ###
